name: CoinBot

on:
  workflow_dispatch:
  # NOTE: 根本是每小時執行一次
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  runUbuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: BwayCer/coinArbitrage.node
          ref: dev/coinBot.min
          token: ${{ secrets.BWAYCER_ACCESS_TOKEN }}
      - name: Run npm install
        run: npm install --production
      - name: Run set config
        run: |
          mkdir -p dist/assets/config
          echo '${{ secrets.CONFIG_TOKEN }}' > dist/assets/config/token.js
      # - name: Run node Savings ALGO
      #   run: node dist/app/coin/savings.js
      - name: Run node PiModule
        run: node dist/app/runCoinPiModule.js

