name: learnApp-2911 Flutter build

on:
  workflow_dispatch:
    inputs:

jobs:
  runUbuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      buildName: release
      zipName: release-linux
    steps:
      - uses: actions/checkout@v3
        with:
          repository: BwayCer/learnApp-2911.dart
          ref: dev/ghAction
          token: ${{ secrets.BWAYCER_ACCESS_TOKEN }}
      - name: git clone minFree.action
        run: git clone https://github.com/BwayCer/minFree.action.git
      - uses: ./minFree.action/.github/actions/install-flutter
        with:
          ghRepo: "3.3.9"
      - run: flutter config --enable-linux-desktop
      # - run: flutter pub get
      # - run: flutter test
      - run: flutter build web
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "18"
      - run: flutter build apk
      # - run: flutter build appbundle
      - name: flutter build linux
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter build linux
      - name: Get release app
        run: |
          mkdir -p $buildName
          mv ./build/web $buildName/web
          mv ./build/app/outputs/apk/release $buildName/apk
          mv ./build/linux/x64/release/bundle $buildName/linuxx64
          # 7z a $zipName.7z $buildName
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.zipName }}
          path: ${{ env.buildName }}
          retention-days: 1
    # https://www.macstadium.com/blog/sharing-variables-between-jobs-in-github-actions
    # outputs:
    #   uniqueVMActionsTag: ${{ steps.spin_up.outputs.uniqueVMActionsTag }}

  runWindows:
    # needs: runUbuntu
    runs-on: windows-latest
    # if:
    defaults:
      run:
        shell: bash
    env:
      buildName: release
      zipName: release-windows
    steps:
      - uses: actions/checkout@v3
        with:
          repository: BwayCer/learnApp-2911.dart
          ref: dev/ghAction
          token: ${{ secrets.BWAYCER_ACCESS_TOKEN }}
      - name: git clone minFree.action
        run: git clone https://github.com/BwayCer/minFree.action.git
      - uses: ./minFree.action/.github/actions/install-flutter
        with:
          ghRepo: "3.3.9"
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - name: Get release app
        shell: powershell
        run: |
          New-Item $env:buildName -ItemType Directory
          Move-Item "./windows/runner/resources" $env:buildName/windows
          # Compress-Archive $env:buildName "$env:zipName.zip"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.zipName }}
          path: ${{ env.buildName }}
          retention-days: 1

